In [1]:
import pandas as pd
from finvizfinance.quote import finvizfinance
import yfinance as yf
from IPython.display import display
from finvizfinance.screener.overview import Overview
from finvizfinance.screener.valuation import Valuation
from finvizfinance.screener.financial import Financial
print("All instaled")

All instaled

In [2]:
stock = finvizfinance('tsla')

In [3]:
stock.ticker_fundament()

{'Company': 'Tesla Inc',
 'Sector': 'Consumer Cyclical',
 'Industry': 'Auto Manufacturers',
 'Country': 'USA',
 'Exchange': 'NASD',
 'Index': 'NDX, S&P 500',
 'P/E': '335.12',
 'EPS (ttm)': '1.08',
 'Insider Own': '28.18%',
 'Shs Outstand': '3.75B',
 'Perf Week': '-3.10%',
 'Market Cap': '1353.09B',
 'Forward P/E': '137.94',
 'EPS next Y': '2.61',
 'Insider Trans': '-0.02%',
 'Shs Float': '2.69B',
 'Perf Month': '-11.17%',
 'Enterprise Value': '1324.09B',
 'PEG': '4.55',
 'EPS next Q': '0.40',
 'Inst Own': '43.20%',
 'Short Float': '2.26%',
 'Perf Quarter': '-19.82%',
 'Income': '3.79B',
 'P/S': '14.27',
 'EPS this Y': '18.56%',
 'Inst Trans': '0.60%',
 'Short Ratio': '0.99',
 'Perf Half Y': '-21.52%',
 'Sales': '94.83B',
 'P/B': '16.47',
 'EPS next Y Percentage': '32.82%',
 'ROA': '2.92%',
 'Short Interest': '60.86M',
 'Perf YTD': '-19.82%',
 'Book/sh': '21.90',
 'P/C': '30.44',
 'EPS next 5Y': '30.30%',
 'ROE': '4.89%',
 '52W High': '498.83 -27.71%',
 'Perf Year': '27.53%',
 'Cash/sh': '11.85',
 'P/FCF': '217.54',
 'EPS past 3/5Y': '-33.28% 38.32%',
 'ROIC': '4.02%',
 '52W Low': '214.25 68.30%',
 'Perf 3Y': '73.81%',
 'Dividend Est.': '-',
 'EV/EBITDA': '120.40',
 'Sales past 3/5Y': '5.19% 24.63%',
 'Gross Margin': '18.03%',
 'Volatility W': '3.23%',
 'Volatility M': '3.01%',
 'Perf 5Y': '63.47%',
 'Dividend TTM': '-',
 'EV/Sales': '13.96',
 'EPS Y/Y TTM': '-47.22%',
 'Oper. Margin': '5.11%',
 'ATR (14)': '14.35',
 'Perf 10Y': '2176.55%',
 'Dividend Ex-Date': '-',
 'Quick Ratio': '1.77',
 'Sales Y/Y TTM': '-2.93%',
 'Profit Margin': '4.00%',
 'RSI (14)': '38.91',
 'Recom': '2.50',
 'Dividend Gr. 3/5Y': '- -',
 'Current Ratio': '2.16',
 'EPS Q/Q': '-63.92%',
 'SMA20': '-6.06%',
 'Beta': '1.93',
 'Target Price': '407.94',
 'Payout': '0.00%',
 'Debt/Eq': '0.18',
 'Sales Q/Q': '-3.14%',
 'SMA50': '-10.63%',
 'Rel Volume': '1.34',
 'Prev Close': '381.26',
 'Employees': '134785',
 'LT Debt/Eq': '0.15',
 'Earnings': 'Apr 22 AMC',
 'SMA200': '-9.15%',
 'Avg Volume': '61.57M',
 'Price': '360.59',
 'IPO': 'Jun 29, 2010',
 'Option/Short': 'Yes / Yes',
 'EPS/Sales Surpr.': '9.94% 0.50%',
 'Trades': '\n\n',
 'Volume': '83,028,568',
 'Change': '-5.42%'}

In [4]:
foverview = Overview()
filters_dict = {'Exchange':'AMEX','Sector':'Basic Materials'}
foverview.set_filter(filters_dict=filters_dict)
df = foverview.screener_view()
df.head()

/opt/anaconda3/envs/quant_finance/lib/python3.12/site-packages/finvizfinance/screener/base.py:134: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([df, pd.DataFrame(frame)], ignore_index=True)

,Ticker,Company,Sector,Industry,Country,Market Cap,P/E,Price,Change,Volume
0,ASM,Avino Silver & Gold Mines Ltd,Basic Materials,Other Precious Metals & Mining,Canada,1.100000e+09,37.49,6.53,-0.0091,4259514.0
1,AUST,Austin Gold Corp,Basic Materials,Gold,Canada,2.109000e+07,NaN,1.54,0.0199,82223.0
2,BTG,B2gold Corp,Basic Materials,Gold,Canada,6.350000e+09,17.73,4.73,-0.0227,22847336.0
3,CITR,CitroTech Inc,Basic Materials,Specialty Chemicals,USA,1.738800e+08,NaN,9.08,0.0861,31118.0
4,CMCL,Caledonia Mining Corporation Plc,Basic Materials,Gold,United Kingdom,4.571400e+08,8.35,23.67,0.0059,112825.0

In [5]:
def company_data(ticker):
    stock= finvizfinance(ticker)
    stock_dict= stock.ticker_fundament()
    
    return stock_dict

stock_dict= company_data("AAPL")

In [6]:
def get_company_area(stock_dict):
    
    stock_areas= {"sector": stock_dict["Sector"],
                  "industry": stock_dict["Industry"],
                  "index":stock_dict["Index"].split(", ")
                  }
    
    return stock_areas

stock_areas= get_company_area(stock_dict)

In [19]:
def get_competition(stock_areas):
    
    # Get them and filter them
    fvaluation = Valuation()
    filters_dict = {'Sector': stock_areas["sector"]}
    fvaluation.set_filter(filters_dict=filters_dict)
    # Get DF
    all_competition_df = fvaluation.screener_view()
    
    fvaluation = Valuation()
    filters_dict = {'Sector': stock_areas["sector"], 'Industry': stock_areas["industry"]}
    fvaluation.set_filter(filters_dict=filters_dict)
    direct_competition_df= fvaluation.screener_view()
    
    indexes_dfs= get_index_companies(stock_areas)
    
    return {'all competition':all_competition_df,
            'direct competition': direct_competition_df, 
            'index competition':indexes_dfs
}
all_dfs = get_competition(stock_areas)

/opt/anaconda3/envs/quant_finance/lib/python3.12/site-packages/finvizfinance/screener/base.py:134: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([df, pd.DataFrame(frame)], ignore_index=True)

/opt/anaconda3/envs/quant_finance/lib/python3.12/site-packages/finvizfinance/screener/base.py:134: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([df, pd.DataFrame(frame)], ignore_index=True)

In [20]:
def get_index_companies(stock_areas):
    
    indexes= {}
    
    #hardcoded because they are only 4 opcions and dificult to get around it
    index_map = {
        "DJIA": "DJIA",
        "NDX": "NASDAQ 100",
        "S&P 500": "S&P 500",
        "RUT": "RUSSELL 2000"
        }
    
    for i in stock_areas["index"]:
        
        #converts the return of the index to find it in screnner
        mapped = index_map.get(i)
        if mapped is None:
            continue
        
        foverview = Overview()
        filters_dict = {'Index': mapped}
        foverview.set_filter(filters_dict=filters_dict)
        data = foverview.screener_view()
        
        indexes[mapped]= data
        
    return indexes

In [21]:
def filter_df(df, market_cap, past_sales_5, eps_next_5):
    df = df.copy()   
    if len(df) > 10:
        df = df[(df['Market Cap'] > market_cap/3) & (df['Market Cap'] < market_cap*3)]

    if len(df) > 10 and past_sales_5 != 0 and 'Sales Past 5Y' in df.columns:
        df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)
        df = df[abs(df['Sales Past 5Y'] - past_sales_5) < 10]

    if len(df) > 10 and eps_next_5 != 0 and 'EPS Next 5Y' in df.columns:
        df['EPS Next 5Y'] = df['EPS Next 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)
        df = df[abs(df['EPS Next 5Y'] - eps_next_5) < 10]
        
    return df

In [22]:
def clean_dfs(all_dfs, ticker):
    
    # Values to evaluate

    df_all_competition= all_dfs['all competition']
    try: 
        market_cap = df_all_competition[df_all_competition['Ticker'] == ticker]['Market Cap'].iloc[0]
    except Exception:
        market_cap = 0
        
    if 'Sales Past 5Y' in df_all_competition.columns:
        try:
            past_sales_5 = df_all_competition[df_all_competition['Ticker'] == ticker]['Sales Past 5Y'].iloc[0]
            past_sales_5 = past_sales_5.replace("%", "").replace('-', "0")
            past_sales_5 = float(past_sales_5)
        except Exception:
            past_sales_5 = 0
    else:
        past_sales_5 = 0
        
    if 'EPS Next 5Y' in df_all_competition.columns:
        try:
            eps_next_5 = df_all_competition[df_all_competition['Ticker'] == ticker]['EPS Next 5Y'].iloc[0]
            eps_next_5 = eps_next_5.replace("%", "").replace('-', "0")
            eps_next_5 = float(eps_next_5)
        except Exception:
            eps_next_5 = 0
    else:
        eps_next_5 = 0
    
    df = filter_df(df_all_competition, market_cap, past_sales_5, eps_next_5)
        
    all_dfs['all competition']=  df
    
    #for the indexes
    df_indexes = all_dfs['index competition']
    
    for i in df_indexes:
        df= filter_df(df_indexes[i], market_cap, past_sales_5, eps_next_5)
        all_dfs[i]=  df
        
    all_dfs.pop("index competition")
    
    for i in all_dfs:
        df= all_dfs[i]["Ticker"]
        all_dfs[i]= df
                
    return all_dfs
        
    
stock_dict= company_data("AAPL")    
all_dfs_clean= clean_dfs(all_dfs, "AAPL")

In [23]:
all_dfs_clean

{'all competition': 1      AAPL
 87     AVGO
 440    MSFT
 479    NVDA
 684     TSM
 Name: Ticker, dtype: object,
 'direct competition': 0     AAPL
 1     AXIL
 2     BOXL
 3     FEBO
 4     FOXX
 5     GMEX
 6     GPRO
 7     KOSS
 8      LPL
 9      MSN
 10    RIME
 11    SONO
 12    SONY
 13    TBCH
 14    UEIC
 15    VUZI
 16    WLDS
 17     WTO
 18    ZEPP
 Name: Ticker, dtype: object,
 'DJIA': 0     AAPL
 2     AMZN
 20    MSFT
 22    NVDA
 Name: Ticker, dtype: object,
 'NASDAQ 100': 0      AAPL
 11     AMZN
 15     AVGO
 43     GOOG
 44    GOOGL
 60     META
 64     MSFT
 68     NVDA
 90     TSLA
 Name: Ticker, dtype: object,
 'S&P 500': 1       AAPL
 31      AMZN
 45      AVGO
 212     GOOG
 213    GOOGL
 305     META
 320     MSFT
 340     NVDA
 447     TSLA
 Name: Ticker, dtype: object}

In [24]:
def all_values(all_dfs_clean, ticker):
   
    table_dfs = {}

    for key in all_dfs_clean: 
        table = []
        for t in all_dfs_clean[key]:  # t is each ticker string
            try:
                
                yfin = yf.Ticker(t).info
                market_cap = yfin.get('marketCap')
                total_debt = yfin.get('totalDebt', 0)
                total_cash = yfin.get('totalCash', 0)
                net_debt = total_debt - total_cash
                enterprise_value = yfin.get('enterpriseValue')
                minority_interest = enterprise_value - market_cap - net_debt
                total_revenue = yfin.get('totalRevenue')
                ebitda = yfin.get('ebitda')
                ev_revenue = enterprise_value / total_revenue
                ev_ebitda = enterprise_value / ebitda
                shares= yfin.get("sharesOutstanding")
                price=yfin.get("previousClose")
                
                temporal_dict = {
                    "ticker": t,  # peer ticker not subject
                    'market cap': market_cap,
                    'net debt': net_debt,
                    'minority interest': minority_interest,
                    'enterprise value': enterprise_value,
                    'total revenue': total_revenue,
                    'ebitda': ebitda,
                    'ev/revenue': ev_revenue,
                    'ev/ebitda': ev_ebitda, 
                    'shares':shares,
                    'price':price
  
            }
                
            except Exception:
                continue 
            table.append(temporal_dict)
        
        table_dfs[key] = pd.DataFrame(table)
    
    return table_dfs

In [25]:
a = all_values(all_dfs_clean, "AAPL")

In [26]:
a['all competition']

,ticker,market cap,net debt,minority interest,enterprise value,total revenue,ebitda,ev/revenue,ev/ebitda,shares,price
0,AAPL,3761492983808,23601999872,-4295618560,3780799365120,435617005568,152901992448,8.679182,24.726946,14681140000,255.63
1,AVGO,1491367493632,51882998784,-2077604864,1541172887552,68281999360,37218000896,22.570705,41.409341,4734668184,313.49
2,MSFT,2775695753216,33816002560,-2520203264,2806991552512,305453006848,175258992640,9.189602,16.016248,7425629076,369.37
3,NVDA,4311464017920,-51144000512,-887127040,4259432890368,215938007040,133230002176,19.725258,31.970523,24300000000,175.75
4,TSM,1758432591872,-2000078045184,7074929508352,6833284055040,3809054294016,2614264070144,1.793958,2.613846,5186504904,341.49

In [53]:
all_competition_df

,Ticker,Market Cap,P/E,Fwd P/E,PEG,P/S,P/B,P/C,P/FCF,EPS This Y,EPS Next Y,EPS Past 5Y,EPS Next 5Y,Sales Past 5Y,Price,Change,Volume
0,AAOI,8.570000e+09,NaN,24.55,NaN,18.80,11.64,39.65,NaN,462.31%,392.58%,24.98%,-,14.20%,113.90,0.1894,16895724.0
1,AAPL,3.694360e+12,31.84,27.05,2.41,8.48,41.95,55.22,29.96,13.66%,9.70%,17.91%,11.22%,8.71%,251.64,0.0006,45151784.0
2,ACFN,4.652000e+07,18.73,NaN,NaN,4.05,5.63,10.45,22.58,-,-,104.28%,-,14.15%,18.56,-0.0226,33214.0
3,ACIW,4.050000e+09,18.39,14.00,NaN,2.30,2.70,20.64,13.08,13.52%,16.15%,28.58%,-,6.34%,39.86,-0.0252,676922.0
4,ACLS,2.900000e+09,24.86,20.92,NaN,3.46,2.80,7.75,27.10,-25.24%,23.67%,20.99%,-,12.07%,94.39,0.1005,1300011.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,ZEPP,1.041200e+08,NaN,NaN,NaN,0.40,0.94,0.92,NaN,-,-,-,-,-22.56%,14.79,0.0602,139304.0
776,ZETA,3.940000e+09,NaN,13.60,0.47,3.02,4.91,12.33,21.30,29.40%,25.75%,17.79%,28.98%,28.80%,16.15,-0.0855,9959206.0
777,ZM,2.239000e+10,12.23,12.35,3.72,4.60,2.29,2.86,11.64,-0.74%,4.70%,22.38%,3.32%,12.92%,75.98,-0.0253,3778127.0
778,ZS,2.242000e+10,NaN,30.50,1.60,7.47,10.19,6.38,25.67,22.19%,14.03%,21.31%,19.03%,44.03%,139.41,-0.0816,3419263.0
779,ZSPC,4.860000e+06,NaN,NaN,NaN,0.15,NaN,1.14,NaN,-5.56%,14.74%,-,-,-,0.15,-0.0665,682407.0

In [55]:
direct_competition_df

,Ticker,Market Cap,P/E,Fwd P/E,PEG,P/S,P/B,P/C,P/FCF,EPS This Y,EPS Next Y,EPS Past 5Y,EPS Next 5Y,Sales Past 5Y,Price,Change,Volume
0,AAPL,3.694360e+12,31.84,27.05,2.41,8.48,41.95,55.22,29.96,13.66%,9.70%,17.91%,11.22%,8.71%,251.64,0.0006,45151784.0
1,AXIL,4.762000e+07,43.86,NaN,NaN,1.72,4.30,9.56,1190.50,-,-,-,-,91.76%,7.00,0.0638,55095.0
2,BOXL,9.800000e+05,NaN,NaN,NaN,0.01,NaN,0.08,NaN,-,-,15.55%,-,32.70%,1.03,0.0000,106182.0
3,FEBO,1.322000e+07,NaN,NaN,NaN,0.95,2.46,3.67,20.98,-,-,-,-,-,1.20,0.0214,1817.0
4,FOXX,2.949000e+07,NaN,NaN,NaN,0.47,NaN,16.66,NaN,-,-,-,-,-,4.21,-0.0047,4171.0
5,GMEX,1.450000e+06,NaN,NaN,NaN,0.43,0.03,0.77,NaN,-,-,-,-,-10.85%,1.03,-0.0804,2386298.0
6,GPRO,1.087000e+08,NaN,NaN,NaN,0.17,1.38,2.19,NaN,-,-,-5.64%,-,-6.09%,0.65,-0.0193,2599075.0
7,KOSS,3.758000e+07,NaN,NaN,NaN,2.94,1.24,2.43,NaN,-,-,-8.23%,-,-7.17%,3.97,-0.0100,19569.0
8,LPL,4.080000e+09,23.19,6.21,0.07,0.22,0.89,3.74,6.26,181.81%,46.31%,-,84.28%,-2.45%,4.08,-0.0490,2513366.0
9,MSN,7.870000e+06,NaN,NaN,NaN,1.19,0.51,0.59,NaN,-,-,-1.89%,-,11.38%,0.37,-0.0209,21542.0
10,RIME,3.510000e+06,NaN,NaN,NaN,0.24,2.30,1.24,NaN,98.54%,44.98%,-,-,-11.87%,1.29,-0.0077,342820.0
11,SONO,1.630000e+09,NaN,48.14,NaN,1.13,3.77,4.48,13.39,161.76%,-11.11%,-22.55%,-,1.70%,13.48,-0.0081,1165566.0
12,SONY,1.227600e+11,NaN,15.58,2.95,1.52,2.36,9.22,6.66,-0.02%,7.38%,7.37%,5.29%,2.32%,20.57,-0.0053,3709561.0
13,TBCH,2.312800e+08,15.14,8.44,0.36,0.72,1.76,13.64,6.79,12.55%,61.25%,-20.14%,23.20%,-2.34%,11.80,0.0155,590161.0
14,UEIC,5.776000e+07,NaN,NaN,NaN,0.16,0.39,1.79,2.92,12.90%,-,-,-,-9.74%,4.49,0.0298,44145.0
15,VUZI,2.029100e+08,NaN,NaN,NaN,32.31,8.02,9.59,NaN,0.00%,-,4.52%,-,-11.52%,2.44,0.0124,702195.0
16,WLDS,4.870000e+06,NaN,NaN,NaN,7.49,0.21,0.26,NaN,-,-,24.74%,-,62.56%,1.38,-0.0282,48260.0
17,WTO,4.600000e+06,NaN,NaN,NaN,0.16,0.19,0.11,NaN,-,-,21.82%,-,4.64%,2.72,0.1013,60074.0
18,ZEPP,1.041200e+08,NaN,NaN,NaN,0.40,0.94,0.92,NaN,-,-,-,-,-22.56%,14.79,0.0602,139304.0

In [39]:
indexes_dfs

{'DJIA':    Ticker                               Company                  Sector  \
 0    AAPL                             Apple Inc              Technology
 1    AMGN                             AMGEN Inc              Healthcare
 2    AMZN                        Amazon.com Inc       Consumer Cyclical
 3     AXP                   American Express Co               Financial
 4      BA                             Boeing Co             Industrials
 5     CAT                       Caterpillar Inc             Industrials
 6     CRM                        Salesforce Inc              Technology
 7    CSCO                    Cisco Systems, Inc              Technology
 8     CVX                          Chevron Corp                  Energy
 9     DIS                        Walt Disney Co  Communication Services
 10     GS              Goldman Sachs Group, Inc               Financial
 11     HD                       Home Depot, Inc       Consumer Cyclical
 12    HON           Honeywell International Inc             Industrials
 13    IBM  International Business Machines Corp              Technology
 14    JNJ                     Johnson & Johnson              Healthcare
 15    JPM                   JPMorgan Chase & Co               Financial
 16     KO                          Coca-Cola Co      Consumer Defensive
 17    MCD                       McDonald's Corp       Consumer Cyclical
 18    MMM                                 3M Co             Industrials
 19    MRK                        Merck & Co Inc              Healthcare
 20   MSFT                 Microsoft Corporation              Technology
 21    NKE                             Nike, Inc       Consumer Cyclical
 22   NVDA                           NVIDIA Corp              Technology
 23     PG                   Procter & Gamble Co      Consumer Defensive
 24    SHW                   Sherwin-Williams Co         Basic Materials
 25    TRV               Travelers Companies Inc               Financial
 26    UNH                Unitedhealth Group Inc              Healthcare
 27      V                              Visa Inc               Financial
 28     VZ            Verizon Communications Inc  Communication Services
 29    WMT                           Walmart Inc      Consumer Defensive

                                Industry Country    Market Cap     P/E   Price  \
 0                  Consumer Electronics     USA  3.694360e+12   31.84  251.64
 1          Drug Manufacturers - General     USA  1.878300e+11   24.48  348.43
 2                       Internet Retail     USA  2.224710e+12   28.89  207.24
 3                       Credit Services     USA  2.073600e+11   19.63  302.00
 4                   Aerospace & Defense     USA  1.542600e+11  103.60  196.42
 5   Farm & Heavy Construction Machinery     USA  3.334400e+11   38.06  716.63
 6                Software - Application     USA  1.689300e+11   23.44  183.02
 7               Communication Equipment     USA  3.193900e+11   28.44   80.86
 8                  Oil & Gas Integrated     USA  4.126300e+11   31.11  206.79
 9                         Entertainment     USA  1.707600e+11   14.20   96.39
 10                      Capital Markets     USA  2.480000e+11   16.29  835.72
 11              Home Improvement Retail     USA  3.295900e+11   23.25  330.91
 12                        Conglomerates     USA  1.408500e+11   27.72  221.57
 13      Information Technology Services     USA  2.256800e+11   21.58  240.59
 14         Drug Manufacturers - General     USA  5.669800e+11   21.30  235.27
 15                  Banks - Diversified     USA  7.886100e+11   14.61  292.40
 16            Beverages - Non-Alcoholic     USA  3.211300e+11   24.57   74.67
 17                          Restaurants     USA  2.186900e+11   25.76  307.84
 18                        Conglomerates     USA  7.725000e+10   24.46  146.67
 19         Drug Manufacturers - General     USA  2.877100e+11   16.00  116.37
 20            Software - Infrastructure     USA  2.767830e+12   23.32  372.74
 21               Footwear & Accessories     USA  7.919000e+10   31.37   53.49
 22                       Semiconductors     USA  4.257360e+12   35.74  175.20
 23        Household & Personal Products     USA  3.327000e+11   21.21  143.16
 24                  Specialty Chemicals     USA  7.773000e+10   30.57  313.70
 25      Insurance - Property & Casualty     USA  6.336000e+10   10.64  293.01
 26                     Healthcare Plans     USA  2.471400e+11   20.64  272.28
 27                      Credit Services     USA  5.789700e+11   28.78  303.76
 28                     Telecom Services     USA  2.147200e+11   12.54   50.91
 29                      Discount Stores     USA  9.730300e+11   44.71  122.05

     Change       Volume
 0   0.0006   45151784.0
 1  -0.0038    2337060.0
 2  -0.0138   35351212.0
 3   0.0003    3639080.0
 4  -0.0100    5691835.0
 5   0.0213    2098290.0
 6  -0.0623   18631394.0
 7   0.0259   23527766.0
 8   0.0077   16695528.0
 9  -0.0159    9155717.0
 10  0.0054    1656051.0
 11  0.0000    4566360.0
 12 -0.0065    3325806.0
 13 -0.0316    4151491.0
 14 -0.0006    9046202.0
 15  0.0086   11092329.0
 16 -0.0059   15653726.0
 17 -0.0020    2955311.0
 18  0.0008    3036877.0
 19  0.0060    7411878.0
 20 -0.0268   42733580.0
 21  0.0148   12073812.0
 22 -0.0025  147664656.0
 23 -0.0058    8567608.0
 24 -0.0008    1914011.0
 25 -0.0085    1250146.0
 26  0.0102    5911688.0
 27 -0.0022    5375944.0
 28  0.0065   20264600.0
 29  0.0110   17269238.0  ,
 'NASDAQ 100':     Ticker                        Company              Sector  \
 0     AAPL                      Apple Inc          Technology
 1     ABNB                     Airbnb Inc   Consumer Cyclical
 2     ADBE                      Adobe Inc          Technology
 3      ADI             Analog Devices Inc          Technology
 4      ADP  Automatic Data Processing Inc          Technology
 ..     ...                            ...                 ...
 96    WDAY                    Workday Inc          Technology
 97     WDC           Western Digital Corp          Technology
 98     WMT                    Walmart Inc  Consumer Defensive
 99     XEL               Xcel Energy, Inc           Utilities
 100     ZS                    Zscaler Inc          Technology

                            Industry Country    Market Cap    P/E   Price  \
 0              Consumer Electronics     USA  3.694360e+12  31.84  251.64
 1                   Travel Services     USA  7.913000e+10  32.16  130.00
 2            Software - Application     USA  9.806000e+10  13.91  238.87
 3                    Semiconductors     USA  1.571200e+11  58.79  321.83
 4            Software - Application     USA  8.250000e+10  19.69  204.89
 ..                              ...     ...           ...    ...     ...
 96           Software - Application     USA  3.323000e+10  50.03  129.29
 97                Computer Hardware     USA  1.020700e+11  30.22  301.05
 98                  Discount Stores     USA  9.730300e+11  44.71  122.05
 99   Utilities - Regulated Electric     USA  4.864000e+10  22.78   77.96
 100       Software - Infrastructure     USA  2.242000e+10    NaN  139.41

      Change      Volume
 0    0.0006  45151784.0
 1   -0.0195   3167535.0
 2   -0.0354   6268314.0
 3    0.0309   3404181.0
 4   -0.0230   3100068.0
 ..      ...         ...
 96  -0.0567   5236636.0
 97   0.0212   7194402.0
 98   0.0110  17269238.0
 99   0.0131   4312674.0
 100 -0.0816   3419263.0

 [101 rows x 10 columns],
 'S&P 500':     Ticker                     Company             Sector  \
 0        A    Agilent Technologies Inc         Healthcare
 1     AAPL                   Apple Inc         Technology
 2     ABBV                  Abbvie Inc         Healthcare
 3     ABNB                  Airbnb Inc  Consumer Cyclical
 4      ABT         Abbott Laboratories         Healthcare
 ..     ...                         ...                ...
 498    XYZ                   Block Inc         Technology
 499    YUM              Yum Brands Inc  Consumer Cyclical
 500    ZBH  Zimmer Biomet Holdings Inc         Healthcare
 501   ZBRA     Zebra Technologies Corp         Technology
 502    ZTS                  Zoetis Inc         Healthcare

                                      Industry Country    Market Cap    P/E  \
 0                      Diagnostics & Research     USA  3.227000e+10  25.18
 1                        Consumer Electronics     USA  3.694360e+12  31.84
 2                Drug Manufacturers - General     USA  3.628300e+11  86.90
 3                             Travel Services     USA  7.913000e+10  32.16
 4                             Medical Devices     USA  1.808200e+11  27.99
 ..                                        ...     ...           ...    ...
 498                 Software - Infrastructure     USA  3.588000e+10  28.45
 499                               Restaurants     USA  4.407000e+10  28.72
 500                           Medical Devices     USA  1.689000e+10  24.34
 501                   Communication Equipment     USA  1.021000e+10  25.41
 502  Drug Manufacturers - Specialty & Generic     USA  4.894000e+10  19.25

       Price  Change      Volume
 0    114.20  0.0195   2076858.0
 1    251.64  0.0006  45151784.0
 2    205.20  0.0013   6990939.0
 3    130.00 -0.0195   3167535.0
 4    104.06 -0.0075  11794332.0
 ..      ...     ...         ...
 498   59.89 -0.0209   4684024.0
 499  159.43  0.0056   1319533.0
 500   86.32 -0.0169   1572183.0
 501  207.49  0.0079    425011.0
 502  115.93  0.0061   4561764.0

 [503 rows x 10 columns]}

In [178]:
Yfin = yf.Ticker("AAPL").info
Yfin

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 54,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1772323200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 251.64,
 'open': 254.02,
 'dayLow': 251.6,
 'dayHigh': 254.98,
 'regularMarketPreviousClose': 251.64,
 'regularMarketOpen': 254.02,
 'regularMarketDayLow': 251.6,
 'regularMarketDayHigh': 254.98,
 'dividendRate': 1.04,
 'dividendYield': 0.41,
 'exDividendDate': 1770595200,
 'payoutRatio': 0.1304,
 'fiveYearAvgDividendYield': 0.52,
 'beta': 1.116,
 'trailingPE': 32.156948,
 'forwardPE': 27.27134,
 'volume': 10997324,
 'regularMarketVolume': 10997323,
 'averageVolume': 46586027,
 'averageVolume10days': 39607800,
 'averageDailyVolume10Day': 41298940,
 'bid': 253.58,
 'ask': 255.98,
 'bidSize': 2,
 'askSize': 4,
 'marketCap': 3733859598336,
 'nonDilutedMarketCap': 3640775908600,
 'fiftyTwoWeekLow': 169.21,
 'fiftyTwoWeekHigh': 288.62,
 'allTimeHigh': 288.62,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 8.571427,
 'fiftyDayAverage': 260.8244,
 'twoHundredDayAverage': 247.32146,
 'trailingAnnualDividendRate': 1.03,
 'trailingAnnualDividendYield': 0.0040931487,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3717963972608,
 'profitMargins': 0.27037,
 'floatShares': 14656182062,
 'sharesOutstanding': 14681140000,
 'sharesShort': 124192030,
 'sharesShortPriorMonth': 133373267,
 'sharesShortPreviousMonthDate': 1770940800,
 'dateShortInterest': 1773360000,
 'sharesPercentSharesOut': 0.0088,
 'heldPercentInsiders': 0.016390001,
 'heldPercentInstitutions': 0.65265,
 'shortRatio': 3.17,
 'shortPercentOfFloat': 0.0085,
 'impliedSharesOutstanding': 14697926000,
 'bookValue': 5.998,
 'priceToBook': 42.3541,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1766793600,
 'earningsQuarterlyGrowth': 0.159,
 'netIncomeToCommon': 117776998400,
 'trailingEps': 7.9,
 'forwardEps': 9.31527,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 8.535,
 'enterpriseToEbitda': 24.316,
 '52WeekChange': 0.123499274,
 'SandP52WeekChange': 0.12811458,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1770595200,
 'quoteType': 'EQUITY',
 'currentPrice': 254.0399,
 'targetHighPrice': 350.0,
 'targetLowPrice': 205.0,
 'targetMeanPrice': 295.31342,
 'targetMedianPrice': 300.0,
 'recommendationMean': 1.89583,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 41,
 'totalCash': 66907000832,
 'totalCashPerShare': 4.557,
 'ebitda': 152901992448,
 'totalDebt': 90509000704,
 'quickRatio': 0.845,
 'currentRatio': 0.974,
 'totalRevenue': 435617005568,
 'debtToEquity': 102.63,
 'revenuePerShare': 29.305,
 'returnOnAssets': 0.24377,
 'returnOnEquity': 1.5202099,
 'grossProfits': 206157004800,
 'freeCashflow': 106312753152,
 'operatingCashflow': 135471996928,
 'earningsGrowth': 0.183,
 'revenueGrowth': 0.157,
 'grossMargins': 0.47325,
 'ebitdaMargins': 0.35099998,
 'operatingMargins': 0.35374,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'longName': 'Apple Inc.',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChange': 2.3999023,
 'regularMarketDayRange': '251.6 - 254.98',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 46939761,
 'fiftyTwoWeekLowChange': 84.829895,
 'fiftyTwoWeekLowChangePercent': 0.50132906,
 'fiftyTwoWeekRange': '169.21 - 288.62',
 'fiftyTwoWeekHighChange': -34.580093,
 'fiftyTwoWeekHighChangePercent': -0.11981184,
 'fiftyTwoWeekChangePercent': 13.591838,
 'dividendDate': 1770854400,
 'earningsTimestamp': 1769720400,
 'earningsTimestampStart': 1777579200,
 'earningsTimestampEnd': 1777579200,
 'earningsCallTimestampStart': 1769724000,
 'earningsCallTimestampEnd': 1769724000,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 7.9,
 'epsForward': 9.31527,
 'epsCurrentYear': 8.5073,
 'priceEpsCurrentYear': 29.8614,
 'fiftyDayAverageChange': -6.7845,
 'fiftyDayAverageChangePercent': -0.026011754,
 'twoHundredDayAverageChange': 6.718445,
 'twoHundredDayAverageChangePercent': 0.027164828,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.9 - Buy',
 'cryptoTradeable': False,
 'shortName': 'Apple Inc.',
 'regularMarketChangePercent': 0.95370466,
 'regularMarketPrice': 254.0399,
 'marketState': 'REGULAR',
 'corporateActions': [],
 'regularMarketTime': 1774456257,
 'displayName': 'Apple',
 'trailingPegRatio': 2.2029}

In [67]:
b= next(iter(a))
c= a[b].columns
for i in c:
    print(i)

ticker
market cap
net debt
minority interest
enterprise value
total revenue
ebitda
ev/revenue
ev/ebitda

In [27]:
all_dataframes= a.copy()
all_dataframes

{'all competition':   ticker     market cap       net debt  minority interest  enterprise value  \
 0   AAPL  3761492983808    23601999872        -4295618560     3780799365120
 1   AVGO  1491367493632    51882998784        -2077604864     1541172887552
 2   MSFT  2775695753216    33816002560        -2520203264     2806991552512
 3   NVDA  4311464017920   -51144000512         -887127040     4259432890368
 4    TSM  1758432591872 -2000078045184      7074929508352     6833284055040

    total revenue         ebitda  ev/revenue  ev/ebitda       shares   price
 0   435617005568   152901992448    8.679182  24.726946  14681140000  255.63
 1    68281999360    37218000896   22.570705  41.409341   4734668184  313.49
 2   305453006848   175258992640    9.189602  16.016248   7425629076  369.37
 3   215938007040   133230002176   19.725258  31.970523  24300000000  175.75
 4  3809054294016  2614264070144    1.793958   2.613846   5186504904  341.49  ,
 'direct competition':    ticker     market cap        net debt  minority interest  enterprise value  \
 0    AAPL  3761492983808     23601999872        -4295618560     3780799365120
 1    AXIL       47891128        -4185734               2486          43707880
 2    BOXL        1047061        32668000           28508999          62224060
 3    FEBO       12611250        -2264000                  0          10347250
 4    FOXX       39299128        19354548                 -8          58653668
 5    GMEX         944850        -2890958            -859782          -2805890
 6    GPRO      126142400        33644000                  0         159786400
 7    KOSS       34836492       -13026405                 -1          21810086
 8     LPL     4010000128  11089120067584      1233109401856    12326239469568
 9     MSN        8501232       -12909000            3310000          -1097768
 10   RIME        7255208         3972000           -5208768           6018440
 11   SONO     1641450624      -304272008                  8        1337178624
 12   SONY   124873129984   -429644054528       357286010880       52515086336
 13   TBCH      199136448        74459000                  8         273595456
 14   UEIC       54801032         1179000           -2056944          53923088
 15   VUZI      196253472       -20147187           10000019         186106304
 16   WLDS        5036836       -18056000           -1000913         -14020077
 17    WTO        4349594      -220668984           -9021554        -225340944
 18   ZEPP      173891248        59259000         2846567640        3079717888

      total revenue         ebitda  ev/revenue   ev/ebitda       shares  \
 0     435617005568   152901992448    8.679182   24.726946  14681140000
 1         27664752        2174769    1.579912   20.097712      6802717
 2        106608000       -4255000    0.583672  -14.623751       951873
 3        108715000      -14634000    0.095178   -0.707069      3062500
 4         62266756       -8716156    0.941974   -6.729305      7005191
 5          5200138       -1012547   -0.539580    2.771121      1824035
 6        651542016      -51737000    0.245243   -3.088436    137903867
 7         12797373       -2747705    1.704263   -7.937565      9466438
 8   25810081677312  4233259122688    0.477575    2.911761   1000000000
 9          6627000       -4685000   -0.165651    0.234315     21042652
 10        26385000      -11066000    0.228101   -0.543868      5758102
 11      1438081024       90337000    0.929835   14.802115    120872657
 12  13170287575040  2036071006208    0.003987    0.025792   5906959969
 13       319913984       33243000    0.855216    8.230167     19600044
 14       368288000        9664000    0.146416    5.579790     12864412
 15         6280611      -29394684   29.631879   -6.331291     83158258
 16          647000       -8248000  -21.669362    1.699815      3597740
 17       212123008     -511519008   -1.062313    0.440533      1692448
 18       258896992      -24213000   11.895534 -127.192743      7042547

        price
 0   255.6300
 1     7.0200
 2     1.2300
 3     1.1400
 4     5.5500
 5     0.5050
 6     0.7175
 7     3.7200
 8     3.9700
 9     0.3830
 10    1.3200
 11   13.7200
 12   21.1200
 13   10.2200
 14    4.1600
 15    2.3500
 16    1.4600
 17    2.6100
 18   11.7100  ,
 'DJIA':   ticker     market cap     net debt  minority interest  enterprise value  \
 0   AAPL  3761492983808  23601999872        -4295618560     3780799365120
 1   AMZN  2251864408064  55518003200             -98304     2307382312960
 2   MSFT  2775695753216  33816002560        -2520203264     2806991552512
 3   NVDA  4311464017920 -51144000512         -887127040     4259432890368

    total revenue        ebitda  ev/revenue  ev/ebitda       shares   price
 0   435617005568  152901992448    8.679182  24.726946  14681140000  255.63
 1   716923994112  145730994176    3.218448  15.833161  10734920870  210.57
 2   305453006848  175258992640    9.189602  16.016248   7425629076  369.37
 3   215938007040  133230002176   19.725258  31.970523  24300000000  175.75  ,
 'NASDAQ 100':   ticker     market cap     net debt  minority interest  enterprise value  \
 0   AAPL  3761492983808  23601999872        -4295618560     3780799365120
 1   AMZN  2251864408064  55518003200             -98304     2307382312960
 2   AVGO  1491367493632  51882998784        -2077604864     1541172887552
 3   GOOG  3562082664448 -59847004160              53248     3502235713536
 4  GOOGL  3577929793536 -59847004160            -208896     3518082580480
 5   META  1453128548352   3488997376            -122880     1456617422848
 6   MSFT  2775695753216  33816002560        -2520203264     2806991552512
 7   NVDA  4311464017920 -51144000512         -887127040     4259432890368
 8   TSLA  1353089417216 -29340001280          728032256     1324477448192

    total revenue        ebitda  ev/revenue   ev/ebitda       shares      price
 0   435617005568  152901992448    8.679182   24.726946  14681140000  255.63000
 1   716923994112  145730994176    3.218448   15.833161  10734920870  210.57000
 2    68281999360   37218000896   22.570705   41.409341   4734668184  313.49000
 3   402835996672  150175006720    8.693949   23.321029   5438000000  294.90000
 4   402835996672  150175006720    8.733288   23.426552   5822000000  297.38998
 5   200965996544  101891997696    7.248079   14.295700   2187177748  579.23000
 6   305453006848  175258992640    9.189602   16.016248   7425629076  369.37000
 7   215938007040  133230002176   19.725258   31.970523  24300000000  175.75000
 8    94827003904   10503000064   13.967302  126.104679   3752431984  381.26000  ,
 'S&P 500':   ticker     market cap     net debt  minority interest  enterprise value  \
 0   AAPL  3761492983808  23601999872        -4295618560     3780799365120
 1   AMZN  2251864408064  55518003200             -98304     2307382312960
 2   AVGO  1491367493632  51882998784        -2077604864     1541172887552
 3   GOOG  3562082664448 -59847004160              53248     3502235713536
 4  GOOGL  3577929793536 -59847004160            -208896     3518082580480
 5   META  1453128548352   3488997376            -122880     1456617422848
 6   MSFT  2775695753216  33816002560        -2520203264     2806991552512
 7   NVDA  4311464017920 -51144000512         -887127040     4259432890368
 8   TSLA  1353089417216 -29340001280          728032256     1324477448192

    total revenue        ebitda  ev/revenue   ev/ebitda       shares      price
 0   435617005568  152901992448    8.679182   24.726946  14681140000  255.63000
 1   716923994112  145730994176    3.218448   15.833161  10734920870  210.57000
 2    68281999360   37218000896   22.570705   41.409341   4734668184  313.49000
 3   402835996672  150175006720    8.693949   23.321029   5438000000  294.90000
 4   402835996672  150175006720    8.733288   23.426552   5822000000  297.38998
 5   200965996544  101891997696    7.248079   14.295700   2187177748  579.23000
 6   305453006848  175258992640    9.189602   16.016248   7425629076  369.37000
 7   215938007040  133230002176   19.725258   31.970523  24300000000  175.75000
 8    94827003904   10503000064   13.967302  126.104679   3752431984  381.26000  }

In [34]:
df= all_dataframes["direct competition"]
df = df.set_index("ticker")
df.head()

,market cap,net debt,minority interest,enterprise value,total revenue,ebitda,ev/revenue,ev/ebitda,shares,price
ticker,,,,,,,,,,
AAPL,3761492983808,23601999872,-4295618560,3780799365120,435617005568,152901992448,8.679182,24.726946,14681140000,255.63
AXIL,47891128,-4185734,2486,43707880,27664752,2174769,1.579912,20.097712,6802717,7.02
BOXL,1047061,32668000,28508999,62224060,106608000,-4255000,0.583672,-14.623751,951873,1.23
FEBO,12611250,-2264000,0,10347250,108715000,-14634000,0.095178,-0.707069,3062500,1.14
FOXX,39299128,19354548,-8,58653668,62266756,-8716156,0.941974,-6.729305,7005191,5.55

In [41]:
df= all_dataframes["direct competition"]
df = df.set_index("ticker")
df.head()

df = df.drop(columns=["shares", "price"])
stocks  = df.loc["AAPL"]
means   = df.mean(numeric_only=True)
medians = df.median(numeric_only=True)
expected  = df.loc["AAPL"].copy()
expected["enterprise value"]= stocks["ebitda"] * medians["ev/ebitda"]
expected["market cap"]= expected["enterprise value"] - stocks["net debt"] - stocks["minority interest"]
expected["ev/ebitda"]= medians["ev/ebitda"]
expected["ev/revenue"]= expected["enterprise value"] / expected["total revenue"]

comparison_df = pd.DataFrame({
    "Mean":     means,
    "Median":   medians,
    "AAPL":     stocks,
    "Expected": expected,
}).T

comparison_df.head()

,market cap,net debt,minority interest,enterprise value,total revenue,ebitda,ev/revenue,ev/ebitda
Mean,2.048910e+11,5.622476e+11,8.363000e+10,8.507686e+11,2.074716e+12,3.379840e+11,1.819003,-4.507050
Median,4.789113e+07,-2.264000e+06,0.000000e+00,5.865367e+07,1.087150e+08,-4.255000e+06,0.477575,0.234315
AAPL,3.761493e+12,2.360200e+10,-4.295619e+09,3.780799e+12,4.356170e+11,1.529020e+11,8.679182,24.726946
Expected,1.652092e+10,2.360200e+10,-4.295619e+09,3.582730e+10,4.356170e+11,1.529020e+11,0.082245,0.234315

In [ ]:
def streamlit_df(all_dataframes, ticker):
    
    streamlit_dfs={}
    for i in all_dataframes:
        df= all_dataframes[i]
        df = df.set_index("ticker")

        df = df.drop(columns=["shares", "price"])
        stocks  = df.loc[ticker]
        means   = df.mean(numeric_only=True)
        medians = df.median(numeric_only=True)
        expected  = df.loc[ticker].copy()
        expected["enterprise value"]= stocks["ebitda"] * medians["ev/ebitda"]
        expected["market cap"]= expected["enterprise value"] - stocks["net debt"] - stocks["minority interest"]
        expected["ev/ebitda"]= medians["ev/ebitda"]
        expected["ev/revenue"]= expected["enterprise value"] / expected["total revenue"]

        comparison_df = pd.DataFrame({
            "Mean":     means,
            "Median":   medians,
            ticker:     stocks,
            "Expected": expected,
        }).T
        streamlit_dfs[i]=comparison_df
    
    return streamlit_dfs

In [272]:
def build_table(all_dataframes, ticker):

    b= next(iter(all_dataframes))
    c= all_dataframes[b].columns
    
    for i in c:
        if i == "price" or i== "shares":
            pass
        else:
            print(f"{i:<20}|",end=" ")

    print("")
    print("_" *20* (len(c)-1))



    for dictionary in all_dataframes:
        print("")
        print(dictionary)
        
        df= all_dataframes[dictionary]
        row= df[df["ticker"] == ticker].iloc[0]
        
        df_no_ticker = df[df["ticker"] != ticker]
        
        for i in c: # Means
            if i == "ticker":
                print(f"{"Mean":<20}|",end=" ")
                
            elif i == "ev/revenue" or i == "ev/ebitda":
                mean= round(df_no_ticker[i].mean(),2)
                print(f"{mean:<20}|",end=" ")
            
            elif i== "price" or i== "shares":
                continue
                
            else:
                mean= round(df_no_ticker[i].mean()/1e6)
                print(f"{mean:<20}|",end=" ")
                
        print("")
        
        for i in c: #Median
            
            if i == "ticker":
                print(f"{"Median":<20}|",end=" ")
                
            elif i == "ev/revenue" or i == "ev/ebitda":
                median= round(df_no_ticker[i].median(),2)
                print(f"{median:<20}|",end=" ")
            
            elif i== "price" or i== "shares":
                continue
            
            else:
                median= round(df_no_ticker[i].median()/1e6)
                print(f"{(median):<20}|",end=" ")
                
        print("")
        
        for i in c: #Ticker
            if i == "ticker":
                print(f"{ticker:<20}|",end=" ")
                
            elif i == "ev/revenue" or i == "ev/ebitda":
                val= round(row[i],2)
                print(f"{val:<20}|",end=" ")
            
            elif i== "price" or i== "shares":
                continue
            
            else:
                val= round(row[i]/1e6)
                print(f"{(val):<20}|",end=" ")
                
        print("")
        print("- " *int(20/2)* (len(c)-1))
        
        df_no_ticker = df_no_ticker.copy()
        ev_ex= row["ebitda"]* df_no_ticker["ev/ebitda"].median()
        row["enterprise value"]= ev_ex
        row["market cap"]= ev_ex - row["net debt"] - row["minority interest"]
        row["ev/ebitda"]= df_no_ticker["ev/ebitda"].median()
                
        for i in c: #Expected
            
            if i == "ticker":
                print(f"{"Expected":<20}|",end=" ")
            
            elif i == "ev/revenue" or i == "ev/ebitda":
                val= round(row[i],2)
                print(f"{round(val,2):<20}|",end=" ")
                
            elif i== "price" or i== "shares":
                continue
            
            else:
                val= round(row[i]/1e6)
                print(f"{(round(val,2)):<20}|",end=" ")
                
        
        print("\n", "_" *20 *(len(c)-1))

In [108]:
all_dataframes= a

In [296]:
def relative_valuation(ticker):
    
    stock_dict= company_data(ticker)
    print("Company data done")
    stock_areas= get_company_area(stock_dict)
    print("Company areas done")
    all_dfs= get_competition(stock_areas)
    print("Company competition done")
    all_dfs_clean= clean_dfs(all_dfs, ticker) 
    print("Company df clean done")   
    all_dataframes = all_values(all_dfs_clean, ticker)
    print("Company all values done")
    build_table(all_dataframes, ticker)
    
relative_valuation("NCLH")

Company data done
Company areas done
Company competition done##########################-] 25/26
Company df clean done
Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | 6945                | 476                 | 2000                | 9421                | 4867                | 809                 | 2.69                | 22.35               |
Median              | 5245                | -534                | 13                  | 10530               | 4513                | 420                 | 2.33                | 24.04               |
NCLH                | 9043                | 15326               | 0                   | 24369               | 9828                | 2546                | 2.48                | 9.57                |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 45883               | 15326               | 0                   | 61209               | 9828                | 2546                | 2.48                | 24.04               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

direct competition
Mean                | 25944               | 1568                | 188                 | 27699               | 11991               | 3123                | 3.14                | 10.07               |
Median              | 4108                | 506                 | 10                  | 4293                | 5261                | 628                 | 2.29                | 12.85               |
NCLH                | 9043                | 15326               | 0                   | 24369               | 9828                | 2546                | 2.48                | 9.57                |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 17399               | 15326               | 0                   | 32725               | 9828                | 2546                | 2.48                | 12.85               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

S&P 500
Mean                | 16913               | 4785                | 178                 | 21875               | 12134               | 1841                | 3.59                | 13.67               |
Median              | 16988               | 3002                | 0                   | 20805               | 7084                | 1647                | 2.66                | 12.82               |
NCLH                | 9043                | 15326               | 0                   | 24369               | 9828                | 2546                | 2.48                | 9.57                |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 17316               | 15326               | 0                   | 32643               | 9828                | 2546                | 2.48                | 12.82               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

In [278]:
Yfin = yf.Ticker("NVDA").info
Yfin
Yfin.get('totalRevenue')

215938007040

In [294]:
tickers = ["NOVT", "MSA", "NOV", "TEL", "DKS", "TSCO", "ULBI", "WINA", "NSSC", "GNTX"]

for ticker in tickers:
    try:
        print(ticker)
        relative_valuation(ticker)
    except Exception as ex:
        print(f"⚠️ {ticker} failed: {ex}")

NOVT
Company data done
Company areas done
Company competition done###########################] 96/97
Company df clean done

/var/folders/hb/3snbzqyx6yd_96gxhv_h781w0000gn/T/ipykernel_71451/105685660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)

Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | 4602                | 88313               | 11025               | 103940              | 206467              | 33840               | 4.1                 | 5.05                |
Median              | 3563                | 68                  | 50                  | 4591                | 1223                | 260                 | 2.96                | 13.39               |
NOVT                | 4228                | -78                 | -30                 | 4120                | 981                 | 178                 | 4.2                 | 23.14               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 2493                | -78                 | -30                 | 2384                | 981                 | 178                 | 4.2                 | 13.39               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

direct competition
Mean                | 8422                | 495                 | 396                 | 9313                | 1677                | 380                 | 15.67               | 14.18               |
Median              | 509                 | -3                  | 3                   | 582                 | 277                 | 34                  | 4.65                | 13.3                |
NOVT                | 4228                | -78                 | -30                 | 4120                | 981                 | 178                 | 4.2                 | 23.14               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 2477                | -78                 | -30                 | 2369                | 981                 | 178                 | 4.2                 | 13.3                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

RUSSELL 2000
Mean                | 3518                | 932                 | 75                  | 4525                | 2242                | 311                 | 38.8                | 6.16                |
Median              | 2843                | 339                 | 20                  | 3725                | 1265                | 242                 | 2.96                | 10.89               |
NOVT                | 4228                | -78                 | -30                 | 4120                | 981                 | 178                 | 4.2                 | 23.14               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 2046                | -78                 | -30                 | 1938                | 981                 | 178                 | 4.2                 | 10.89               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________
MSA
Company data done
Company areas done

/opt/anaconda3/envs/quant_finance/lib/python3.12/site-packages/finvizfinance/screener/base.py:134: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([df, pd.DataFrame(frame)], ignore_index=True)
/var/folders/hb/3snbzqyx6yd_96gxhv_h781w0000gn/T/ipykernel_71451/105685660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)

Company competition done
Company df clean done
Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | 7978                | 1990                | 865                 | 10833               | 5469                | 857                 | 66.19               | 12.78               |
Median              | 6912                | 901                 | 155                 | 8865                | 3939                | 644                 | 2.35                | 13.69               |
MSA                 | 6565                | 475                 | 264                 | 7304                | 1875                | 482                 | 3.9                 | 15.16               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 5857                | 475                 | 264                 | 6596                | 1875                | 482                 | 3.9                 | 13.69               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

direct competition
Mean                | 1637                | 728                 | 29                  | 2394                | 1082                | 278                 | 2.33                | 1.46                |
Median              | 284                 | -3                  | 0                   | 226                 | 158                 | 26                  | 1.45                | 8.59                |
MSA                 | 6565                | 475                 | 264                 | 7304                | 1875                | 482                 | 3.9                 | 15.16               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 3398                | 475                 | 264                 | 4137                | 1875                | 482                 | 3.9                 | 8.59                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________
NOV
Company data done
Company areas done
Company competition done#################----------] 2/3 3
Company df clean done

/var/folders/hb/3snbzqyx6yd_96gxhv_h781w0000gn/T/ipykernel_71451/105685660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)

Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | ⚠️ NOV failed: cannot convert float NaN to integer
TEL
Company data done
Company areas done
Company competition done##########################-] 25/26
Company df clean done

/var/folders/hb/3snbzqyx6yd_96gxhv_h781w0000gn/T/ipykernel_71451/105685660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)

Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | 61149               | 2520                | 3553                | 67222               | 25877               | 7068                | 5.52                | 20.58               |
Median              | 45831               | 2171                | 612                 | 50338               | 11719               | 3004                | 4.98                | 14.18               |
TEL                 | 59646               | 4751                | 2130                | 66527               | 18095               | 4517                | 3.68                | 14.73               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 57193               | 4751                | 2130                | 64074               | 18095               | 4517                | 3.68                | 14.18               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

direct competition
Mean                | 10039               | 363                 | 707                 | 11109               | 3373                | 459                 | 8.66                | 47.51               |
Median              | 1006                | 0                   | 41                  | 990                 | 548                 | 58                  | 2.79                | 14.86               |
TEL                 | 59646               | 4751                | 2130                | 66527               | 18095               | 4517                | 3.68                | 14.73               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 60226               | 4751                | 2130                | 67107               | 18095               | 4517                | 3.68                | 14.86               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

S&P 500
Mean                | 60458               | 12150               | 913                 | 73521               | 29510               | 4935                | 5.45                | 32.26               |
Median              | 47684               | 6802                | 297                 | 59496               | 15524               | 3642                | 4.17                | 15.38               |
TEL                 | 59646               | 4751                | 2130                | 66527               | 18095               | 4517                | 3.68                | 14.73               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 62603               | 4751                | 2130                | 69484               | 18095               | 4517                | 3.68                | 15.38               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________
DKS
Company data done
Company areas done
Company competition done#################----------] 2/3 8
Company df clean done

/var/folders/hb/3snbzqyx6yd_96gxhv_h781w0000gn/T/ipykernel_71451/105685660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)

Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | 16551               | 3648                | 2562                | 22762               | 12884               | 1815                | 2.34                | 13.56               |
Median              | 13655               | 2515                | 177                 | 17517               | 10815               | 1514                | 1.93                | 11.89               |
DKS                 | 17305               | 6393                | -41                 | 23657               | 17215               | 1980                | 1.37                | 11.95               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 17199               | 6393                | -41                 | 23551               | 17215               | 1980                | 1.37                | 11.89               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

direct competition
Mean                | 3782                | 969                 | 634                 | 5385                | 4646                | 481                 | 3.52                | -16.55              |
Median              | 584                 | 437                 | 5                   | 1290                | 1585                | 81                  | 0.85                | 8.06                |
DKS                 | 17305               | 6393                | -41                 | 23657               | 17215               | 1980                | 1.37                | 11.95               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 9611                | 6393                | -41                 | 15963               | 17215               | 1980                | 1.37                | 8.06                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________
TSCO
Company data done
Company areas done
Company competition done##########################-] 25/26
Company df clean done

/var/folders/hb/3snbzqyx6yd_96gxhv_h781w0000gn/T/ipykernel_71451/105685660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)

Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | 23879               | 195228              | 8406                | 227513              | 492322              | 27833               | 2.39                | 12.82               |
Median              | 19129               | 3487                | 172                 | 22323               | 12365               | 1980                | 1.7                 | 11.93               |
TSCO                | 24154               | 5749                | 37                  | 29940               | 15524               | 1961                | 1.93                | 15.26               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 17617               | 5749                | 37                  | 23403               | 15524               | 1961                | 1.93                | 11.93               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

direct competition
Mean                | 3630                | 983                 | 633                 | 5245                | 4684                | 481                 | 3.5                 | -16.63              |
Median              | 584                 | 437                 | 3                   | 1290                | 1585                | 81                  | 0.85                | 8.06                |
TSCO                | 24154               | 5749                | 37                  | 29940               | 15524               | 1961                | 1.93                | 15.26               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 10027               | 5749                | 37                  | 15813               | 15524               | 1961                | 1.93                | 8.06                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

S&P 500
Mean                | 30519               | 8630                | 455                 | 39604               | 19413               | 2945                | 4.55                | 35.96               |
Median              | 25851               | 4521                | 166                 | 32481               | 9370                | 2185                | 3.52                | 14.13               |
TSCO                | 24154               | 5749                | 37                  | 29940               | 15524               | 1961                | 1.93                | 15.26               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 21928               | 5749                | 37                  | 27713               | 15524               | 1961                | 1.93                | 14.13               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________
ULBI
Company data done
Company areas done
Company competition done#################----------] 2/3 5
Company df clean done

/var/folders/hb/3snbzqyx6yd_96gxhv_h781w0000gn/T/ipykernel_71451/105685660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)

Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | 147                 | 72                  | 19                  | 238                 | 375                 | 4                   | 7.72                | 878.3               |
Median              | 125                 | 12                  | 3                   | 145                 | 158                 | 6                   | 1.12                | 7.88                |
ULBI                | 110                 | 43                  | 3                   | 156                 | 191                 | 12                  | 0.82                | 13.18               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 47                  | 43                  | 3                   | 94                  | 191                 | 12                  | 0.82                | 7.88                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

direct competition
Mean                | 5496                | 293                 | 453                 | 6241                | 1063                | 147                 | 92.07               | 4.73                |
Median              | 364                 | 15                  | 16                  | 460                 | 95                  | -4                  | 2.53                | -1.03               |
ULBI                | 110                 | 43                  | 3                   | 156                 | 191                 | 12                  | 0.82                | 13.18               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | -59                 | 43                  | 3                   | -12                 | 191                 | 12                  | 0.82                | -1.03               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________
WINA
Company data done
Company areas done
Company competition done###########################] 96/97
Company df clean done

/var/folders/hb/3snbzqyx6yd_96gxhv_h781w0000gn/T/ipykernel_71451/105685660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)

Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | 2161                | 1427                | 1892                | 5479                | 3766                | 381                 | 4.55                | -7.12               |
Median              | 2179                | 1031                | 15                  | 3568                | 2839                | 276                 | 1.05                | 9.68                |
WINA                | 1532                | 53                  | 3                   | 1588                | 86                  | 55                  | 18.46               | 28.7                |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 479                 | 53                  | 3                   | 536                 | 86                  | 55                  | 18.46               | 9.68                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

direct competition
Mean                | 4133                | 1110                | 633                 | 5876                | 5027                | 524                 | 3.14                | -16.92              |
Median              | 584                 | 551                 | 5                   | 1290                | 1679                | 87                  | 0.85                | 8.06                |
WINA                | 1532                | 53                  | 3                   | 1588                | 86                  | 55                  | 18.46               | 28.7                |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 390                 | 53                  | 3                   | 446                 | 86                  | 55                  | 18.46               | 8.06                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

RUSSELL 2000
Mean                | 1830                | 652                 | 31                  | 2513                | 1696                | 198                 | 27.42               | -0.14               |
Median              | 1548                | 177                 | 9                   | 1981                | 869                 | 136                 | 2.12                | 9.73                |
WINA                | 1532                | 53                  | 3                   | 1588                | 86                  | 55                  | 18.46               | 28.7                |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 482                 | 53                  | 3                   | 538                 | 86                  | 55                  | 18.46               | 9.73                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________
NSSC
Company data done
Company areas done

/opt/anaconda3/envs/quant_finance/lib/python3.12/site-packages/finvizfinance/screener/base.py:134: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([df, pd.DataFrame(frame)], ignore_index=True)

Company competition done###########################] 96/97
Company df clean done

/var/folders/hb/3snbzqyx6yd_96gxhv_h781w0000gn/T/ipykernel_71451/105685660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)

Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | 2020                | 599                 | 20                  | 2638                | 1476                | 251                 | 2.61                | 14.14               |
Median              | 1878                | 306                 | 15                  | 2466                | 854                 | 176                 | 2.39                | 12.39               |
NSSC                | 1388                | -110                | 92                  | 1370                | 192                 | 55                  | 7.13                | 25.11               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 694                 | -110                | 92                  | 676                 | 192                 | 55                  | 7.13                | 12.39               |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

direct competition
Mean                | 1884                | 756                 | 37                  | 2677                | 1162                | 299                 | 2.17                | 0.99                |
Median              | 284                 | -1                  | 0                   | 226                 | 158                 | 26                  | 1.45                | 8.59                |
NSSC                | 1388                | -110                | 92                  | 1370                | 192                 | 55                  | 7.13                | 25.11               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 486                 | -110                | 92                  | 468                 | 192                 | 55                  | 7.13                | 8.59                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

RUSSELL 2000
Mean                | 1698                | 637                 | 28                  | 2363                | 1631                | 187                 | 26.62               | -3.72               |
Median              | 1462                | 171                 | 7                   | 1859                | 822                 | 124                 | 2.09                | 9.5                 |
NSSC                | 1388                | -110                | 92                  | 1370                | 192                 | 55                  | 7.13                | 25.11               |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 536                 | -110                | 92                  | 518                 | 192                 | 55                  | 7.13                | 9.5                 |
 ________________________________________________________________________________________________________________________________________________________________________________________________________
GNTX
Company data done
Company areas done
Company competition done#################----------] 2/3 8
Company df clean done

/var/folders/hb/3snbzqyx6yd_96gxhv_h781w0000gn/T/ipykernel_71451/105685660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales Past 5Y'] = df['Sales Past 5Y'].str.replace('%', '').str.replace('-', '0').astype(float)

Company all values done
ticker              | market cap          | net debt            | minority interest   | enterprise value    | total revenue       | ebitda              | ev/revenue          | ev/ebitda           |
________________________________________________________________________________________________________________________________________________________________________________________________________

all competition
Mean                | 5359                | 2001                | 157                 | 7517                | 8656                | 970                 | 1.62                | 10.57               |
Median              | 4411                | 1742                | 15                  | 6498                | 4976                | 746                 | 1.27                | 9.41                |
GNTX                | 4828                | -139                | -101                | 4588                | 2534                | 590                 | 1.81                | 7.78                |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 5789                | -139                | -101                | 5550                | 2534                | 590                 | 1.81                | 9.41                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________

direct competition
Mean                | 5401                | 1307                | 72                  | 6780                | 5459                | 624                 | 13.53               | 15.81               |
Median              | 848                 | 246                 | 9                   | 1157                | 1483                | 132                 | 0.86                | 7.06                |
GNTX                | 4828                | -139                | -101                | 4588                | 2534                | 590                 | 1.81                | 7.78                |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Expected            | 4401                | -139                | -101                | 4162                | 2534                | 590                 | 1.81                | 7.06                |
 ________________________________________________________________________________________________________________________________________________________________________________________________________